### ISSUE TITLE
Stories folder missing

### ISSUE THREAD

**Issue by jvondermarck** [kiancliffe/Conquest-Of-Munster#11]
The "Stories" folder is missing so we can't play the game (there is even no error message because the folder is missing it can be great to add a message when it's not possible to find the folder) and we can't really contribute to the game if we don't have the stories ?
Thanks.

**Comment by SirShamrock** [comment]
Apologies for the delayed response. I was focusing on other work at the moment so didn't have time to check Github. The story_folder is no longer needed. Download the updated engine.py and template.py, and that's all you need to get started. Instructions on how to use them will be uploaded shortly.
