### ISSUE TITLE
problem with game input

### ISSUE THREAD

**Issue by filegrunt** [kiancliffe/Conquest-Of-Munster#16]
**Describe the bug**

**To Reproduce**
cloned repo
python template.py 

create ch file

python engine.py
ran output hello prompt but nothing else

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/101126101/166723627-365218bb-3a7a-4abb-9661-47441dd245d3.png)

**Desktop (please complete the following information):**
windows 10  dos command line

**Comment by SirShamrock** [comment]
Hi, thanks for the report. Did you run the game file first with python, such as 'template.py' before running the engine file?

**Comment by SirShamrock** [comment]
Template updated to show users to press 'enter' to continue. Thanks filegrunt for finding the issue.
