### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by SirShamrock** [kiancliffe/Conquest-Of-Munster#5]
Make changes to the readme file, as the project idea has changed from making a text-based adventure game to instead making a game engine that allows users to play text-based adventure games and create their own

**Comment by SirShamrock** [comment]
Readme must also be updated to show how to install the project, how to run it, how to play games, and how to create games

**Comment by lukasgrabowicz** [comment]
Hi @SirShamrock . Any tip on how the game should be installed? Is it just a matter of installing the Python on the machine and double clicking into main.py?
Thanks

**Comment by jvondermarck** [comment]
@lukasgrabowicz Hi, Yes you have to install Python 3 first, and then type this command to run the program `python3 main.py`.
To be sure you have installed python just check in your terminal this command : `python --version`, you should get your python version (like 3.9)
