### ISSUE TITLE
Impossible to run the main program (import error)

### ISSUE THREAD

**Issue by jvondermarck** [kiancliffe/Conquest-Of-Munster#9]
**Describe the bug**
It is impossible for me to run the program because at line 10 there is : `import engine`. 
I tried to write the command `pip install engine` it doesn't work and I also look on internet, they're talking to use the command `pip install pyttsx3`. 
There is no documentation on your repository, so I ask the question here to know how to run your program.

**Screenshots**
![image](https://user-images.githubusercontent.com/62793491/159925479-81560f42-5dbd-4907-8219-98deeae64313.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Python 3.9.10

**Comment by azh412** [comment]
What specifically happens when you attempt to use `pip`?

**Comment by jvondermarck** [comment]
@azh412 I just don't know how to install the package "engine" with the pip command.

**Comment by azh412** [comment]
Ah I see, I reproduced the error. Possible documentation on how to install the module `engine` would help.

**Comment by jvondermarck** [comment]
Yup! So which command did you use to install the package engine? I haven't found anything working on internet..

**Comment by azh412** [comment]
> I haven't found anything working on internet..

Yeah me neither.

**Comment by jvondermarck** [comment]
I don't get it, how did you do to install this package while it's you who wrote the code? 🤔

**Comment by azh412** [comment]
I came here while hunting for issues to solve, I didn't write the code.

**Comment by jvondermarck** [comment]
Oh yea my bad, sorry! Thanks for helping me @azh412 👌

**Comment by SirShamrock** [comment]
Sorry, engine file is uploaded now.
